<a href="https://colab.research.google.com/github/HikaruEgashira/pytorch-tutorial/blob/master/01what_is_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
!python --version

Python 3.6.7


In [0]:
!pip install torch torchvision

In [1]:
import torch
torch.cuda.is_available()

True

In [0]:
from __future__ import print_function
import torch

In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[2.9917e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [6.5993e-10, 4.2419e-08, 3.3707e-06],
        [8.1265e+20, 2.0798e+20, 1.3075e+22],
        [8.2293e-10, 3.2915e-09, 0.0000e+00]])


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7011, 0.3504, 0.7226],
        [0.2043, 0.8487, 0.9005],
        [0.1257, 0.0286, 0.1396],
        [0.9005, 0.5098, 0.5849],
        [0.0468, 0.3478, 0.0605]])


In [10]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


new_* の形はサイズをとる

In [12]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.6807,  0.8508, -1.8713],
        [-0.6115, -1.7489,  0.2549],
        [-0.5960, -1.2273,  1.8745],
        [-0.3945,  0.7616,  0.6555],
        [ 0.0613, -0.6850,  3.1959]])


In [13]:
print(torch.ones(5, 3, dtype=torch.long))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


torch.size関数はタプルtupple

In [14]:
print(x.size())

torch.Size([5, 3])


In [17]:
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

tensor([[-0.9607,  1.8174, -0.9972],
        [-0.0476, -1.0685,  1.1992],
        [ 0.2992, -0.9975,  2.1805],
        [ 0.5217,  1.6803,  0.7940],
        [ 1.0188, -0.5865,  3.2245]])
tensor([[-0.9607,  1.8174, -0.9972],
        [-0.0476, -1.0685,  1.1992],
        [ 0.2992, -0.9975,  2.1805],
        [ 0.5217,  1.6803,  0.7940],
        [ 1.0188, -0.5865,  3.2245]])


結果をoutで指定して格納できる

In [18]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9607,  1.8174, -0.9972],
        [-0.0476, -1.0685,  1.1992],
        [ 0.2992, -0.9975,  2.1805],
        [ 0.5217,  1.6803,  0.7940],
        [ 1.0188, -0.5865,  3.2245]])


y += x

In [19]:
y.add_(x)
print(y)

tensor([[-0.9607,  1.8174, -0.9972],
        [-0.0476, -1.0685,  1.1992],
        [ 0.2992, -0.9975,  2.1805],
        [ 0.5217,  1.6803,  0.7940],
        [ 1.0188, -0.5865,  3.2245]])


In [20]:
x

tensor([[-1.6807,  0.8508, -1.8713],
        [-0.6115, -1.7489,  0.2549],
        [-0.5960, -1.2273,  1.8745],
        [-0.3945,  0.7616,  0.6555],
        [ 0.0613, -0.6850,  3.1959]])

In [25]:
x[:, 1]

tensor([-0.9448,  1.0896, -1.5415, -0.6245])

viewでsizeの整形
-1も指定でき、その場合もう一つの引数にあうように

In [24]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [27]:
x = torch.randn(1)
print(x)
% python number
print(x.item())

tensor([0.0134])
0.013429779559373856


In [28]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


copyである

In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


numpy to tensor

In [32]:
import numpy as np
a =  np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [33]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))

tensor([1.0134], device='cuda:0')
tensor([1.0134], dtype=torch.float64)
