<a href="https://colab.research.google.com/github/HikaruEgashira/pytorch-tutorial/blob/master/02_autograd_automatic_differentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

自動微分

In [0]:
import torch

In [0]:
torch.cuda.is_available()

True

In [0]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [0]:
print(y.grad_fn)

In [0]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


.requires_grad_() で現在のフラグを置き換えることができる
何も与えていなければfalseを返す

In [0]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


Gradients

In [0]:
out

tensor(27., grad_fn=<MeanBackward1>)

In [0]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [0]:
out.backward()

In [0]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [0]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
  y *= 2
  
print(y)

tensor([-65.2968, 605.1617, 964.7529], grad_fn=<MulBackward0>)


In [0]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [0]:
z = torch.randn(1)
print(z, z.requires_grad)

tensor([-1.9989]) False


In [0]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False
